
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatLab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatLab
  pod 'TwilioChatClient', '2.2.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'


  
  target 'ChatLabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatLabUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
