# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Gets version of the project"
  lane :version do
    v = get_version_number(xcodeproj: "chatLab.xcodeproj")
    puts v
  end

  desc "Bumps version. Type: Patch"
  lane :version_patch do
    increment_version_number(bump_type: "patch")
  end
end
